### ISSUE TITLE
Unable to complete

### ISSUE THREAD

**Issue by simonasdmd** [felipe-fg/batch-blender-godot-exporter#1]
I executed the script using CMD. But the results were not successful. "Bpy. Ops. Export_scene. DAE" is missing according to the prompt, but I don't know what it is

![image](https://user-images.githubusercontent.com/42527845/77892975-ed9ed080-72a5-11ea-977a-7cb782645007.png)

**Comment by felipe-fg** [comment]
Hello.

It looks like you don't have the Godot's Collada Exporter addon installed.
Check this project for more info: https://github.com/godotengine/collada-exporter

The purpose of this Python script is just to automate the steps and clicks in the Blender UI, especially with a lot of models to convert.

I've tested again and it still works using Blender 2.79 (but not with 2.8x).
